################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../DSP/Source/FilteringFunctions/arm_conv_f32.c \
../DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../DSP/Source/FilteringFunctions/arm_conv_q15.c \
../DSP/Source/FilteringFunctions/arm_conv_q31.c \
../DSP/Source/FilteringFunctions/arm_conv_q7.c \
../DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_f32.c \
../DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_q7.c \
../DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../DSP/Source/FilteringFunctions/arm_lms_f32.c \
../DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../DSP/Source/FilteringFunctions/arm_lms_q15.c \
../DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./DSP/Source/FilteringFunctions/arm_conv_f32.o \
./DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./DSP/Source/FilteringFunctions/arm_conv_q15.o \
./DSP/Source/FilteringFunctions/arm_conv_q31.o \
./DSP/Source/FilteringFunctions/arm_conv_q7.o \
./DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_f32.o \
./DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_q7.o \
./DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./DSP/Source/FilteringFunctions/arm_lms_f32.o \
./DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./DSP/Source/FilteringFunctions/arm_lms_q15.o \
./DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./DSP/Source/FilteringFunctions/arm_conv_f32.d \
./DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./DSP/Source/FilteringFunctions/arm_conv_q15.d \
./DSP/Source/FilteringFunctions/arm_conv_q31.d \
./DSP/Source/FilteringFunctions/arm_conv_q7.d \
./DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_f32.d \
./DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_q7.d \
./DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./DSP/Source/FilteringFunctions/arm_lms_f32.d \
./DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./DSP/Source/FilteringFunctions/arm_lms_q15.d \
./DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
DSP/Source/FilteringFunctions/%.o DSP/Source/FilteringFunctions/%.su DSP/Source/FilteringFunctions/%.cyclo: ../DSP/Source/FilteringFunctions/%.c DSP/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -D__FPU_PRESENT=1U -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32F401xE -c -I../Core/Inc -I"C:/Users/gssan/OneDrive/Documentos/GitHub/STM32_ApliacionesAvanzadas/prueba3/DSP/Include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-DSP-2f-Source-2f-FilteringFunctions

clean-DSP-2f-Source-2f-FilteringFunctions:
	-$(RM) ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./DSP/Source/FilteringFunctions/arm_conv_f32.cyclo ./DSP/Source/FilteringFunctions/arm_conv_f32.d ./DSP/Source/FilteringFunctions/arm_conv_f32.o ./DSP/Source/FilteringFunctions/arm_conv_f32.su ./DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./DSP/Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./DSP/Source/FilteringFunctions/arm_conv_fast_q15.d ./DSP/Source/FilteringFunctions/arm_conv_fast_q15.o ./DSP/Source/FilteringFunctions/arm_conv_fast_q15.su ./DSP/Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./DSP/Source/FilteringFunctions/arm_conv_fast_q31.d ./DSP/Source/FilteringFunctions/arm_conv_fast_q31.o ./DSP/Source/FilteringFunctions/arm_conv_fast_q31.su ./DSP/Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./DSP/Source/FilteringFunctions/arm_conv_opt_q15.d ./DSP/Source/FilteringFunctions/arm_conv_opt_q15.o ./DSP/Source/FilteringFunctions/arm_conv_opt_q15.su ./DSP/Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./DSP/Source/FilteringFunctions/arm_conv_opt_q7.d ./DSP/Source/FilteringFunctions/arm_conv_opt_q7.o ./DSP/Source/FilteringFunctions/arm_conv_opt_q7.su ./DSP/Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./DSP/Source/FilteringFunctions/arm_conv_partial_f32.d ./DSP/Source/FilteringFunctions/arm_conv_partial_f32.o ./DSP/Source/FilteringFunctions/arm_conv_partial_f32.su ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o
	-$(RM) ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./DSP/Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./DSP/Source/FilteringFunctions/arm_conv_partial_q15.d ./DSP/Source/FilteringFunctions/arm_conv_partial_q15.o ./DSP/Source/FilteringFunctions/arm_conv_partial_q15.su ./DSP/Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./DSP/Source/FilteringFunctions/arm_conv_partial_q31.d ./DSP/Source/FilteringFunctions/arm_conv_partial_q31.o ./DSP/Source/FilteringFunctions/arm_conv_partial_q31.su ./DSP/Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./DSP/Source/FilteringFunctions/arm_conv_partial_q7.d ./DSP/Source/FilteringFunctions/arm_conv_partial_q7.o ./DSP/Source/FilteringFunctions/arm_conv_partial_q7.su ./DSP/Source/FilteringFunctions/arm_conv_q15.cyclo ./DSP/Source/FilteringFunctions/arm_conv_q15.d ./DSP/Source/FilteringFunctions/arm_conv_q15.o ./DSP/Source/FilteringFunctions/arm_conv_q15.su ./DSP/Source/FilteringFunctions/arm_conv_q31.cyclo ./DSP/Source/FilteringFunctions/arm_conv_q31.d ./DSP/Source/FilteringFunctions/arm_conv_q31.o ./DSP/Source/FilteringFunctions/arm_conv_q31.su ./DSP/Source/FilteringFunctions/arm_conv_q7.cyclo ./DSP/Source/FilteringFunctions/arm_conv_q7.d ./DSP/Source/FilteringFunctions/arm_conv_q7.o ./DSP/Source/FilteringFunctions/arm_conv_q7.su ./DSP/Source/FilteringFunctions/arm_correlate_f32.cyclo ./DSP/Source/FilteringFunctions/arm_correlate_f32.d ./DSP/Source/FilteringFunctions/arm_correlate_f32.o ./DSP/Source/FilteringFunctions/arm_correlate_f32.su ./DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./DSP/Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d ./DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o ./DSP/Source/FilteringFunctions/arm_correlate_fast_q15.su ./DSP/Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d ./DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o ./DSP/Source/FilteringFunctions/arm_correlate_fast_q31.su ./DSP/Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d ./DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o ./DSP/Source/FilteringFunctions/arm_correlate_opt_q15.su ./DSP/Source/FilteringFunctions/arm_correlate_opt_q7.cyclo ./DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d ./DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o ./DSP/Source/FilteringFunctions/arm_correlate_opt_q7.su ./DSP/Source/FilteringFunctions/arm_correlate_q15.cyclo ./DSP/Source/FilteringFunctions/arm_correlate_q15.d ./DSP/Source/FilteringFunctions/arm_correlate_q15.o ./DSP/Source/FilteringFunctions/arm_correlate_q15.su ./DSP/Source/FilteringFunctions/arm_correlate_q31.cyclo ./DSP/Source/FilteringFunctions/arm_correlate_q31.d ./DSP/Source/FilteringFunctions/arm_correlate_q31.o ./DSP/Source/FilteringFunctions/arm_correlate_q31.su ./DSP/Source/FilteringFunctions/arm_correlate_q7.cyclo ./DSP/Source/FilteringFunctions/arm_correlate_q7.d ./DSP/Source/FilteringFunctions/arm_correlate_q7.o ./DSP/Source/FilteringFunctions/arm_correlate_q7.su ./DSP/Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d ./DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o ./DSP/Source/FilteringFunctions/arm_fir_decimate_f32.su ./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./DSP/Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d ./DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o ./DSP/Source/FilteringFunctions/arm_fir_decimate_q15.su
	-$(RM) ./DSP/Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d ./DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o ./DSP/Source/FilteringFunctions/arm_fir_decimate_q31.su ./DSP/Source/FilteringFunctions/arm_fir_f32.cyclo ./DSP/Source/FilteringFunctions/arm_fir_f32.d ./DSP/Source/FilteringFunctions/arm_fir_f32.o ./DSP/Source/FilteringFunctions/arm_fir_f32.su ./DSP/Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_fast_q15.d ./DSP/Source/FilteringFunctions/arm_fir_fast_q15.o ./DSP/Source/FilteringFunctions/arm_fir_fast_q15.su ./DSP/Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_fast_q31.d ./DSP/Source/FilteringFunctions/arm_fir_fast_q31.o ./DSP/Source/FilteringFunctions/arm_fir_fast_q31.su ./DSP/Source/FilteringFunctions/arm_fir_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_fir_init_f32.d ./DSP/Source/FilteringFunctions/arm_fir_init_f32.o ./DSP/Source/FilteringFunctions/arm_fir_init_f32.su ./DSP/Source/FilteringFunctions/arm_fir_init_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_init_q15.d ./DSP/Source/FilteringFunctions/arm_fir_init_q15.o ./DSP/Source/FilteringFunctions/arm_fir_init_q15.su ./DSP/Source/FilteringFunctions/arm_fir_init_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_init_q31.d ./DSP/Source/FilteringFunctions/arm_fir_init_q31.o ./DSP/Source/FilteringFunctions/arm_fir_init_q31.su ./DSP/Source/FilteringFunctions/arm_fir_init_q7.cyclo ./DSP/Source/FilteringFunctions/arm_fir_init_q7.d ./DSP/Source/FilteringFunctions/arm_fir_init_q7.o ./DSP/Source/FilteringFunctions/arm_fir_init_q7.su ./DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./DSP/Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d ./DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o ./DSP/Source/FilteringFunctions/arm_fir_lattice_f32.su ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./DSP/Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d ./DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o ./DSP/Source/FilteringFunctions/arm_fir_lattice_q15.su ./DSP/Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d ./DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o ./DSP/Source/FilteringFunctions/arm_fir_lattice_q31.su ./DSP/Source/FilteringFunctions/arm_fir_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_q15.d ./DSP/Source/FilteringFunctions/arm_fir_q15.o ./DSP/Source/FilteringFunctions/arm_fir_q15.su ./DSP/Source/FilteringFunctions/arm_fir_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_q31.d ./DSP/Source/FilteringFunctions/arm_fir_q31.o ./DSP/Source/FilteringFunctions/arm_fir_q31.su ./DSP/Source/FilteringFunctions/arm_fir_q7.cyclo ./DSP/Source/FilteringFunctions/arm_fir_q7.d ./DSP/Source/FilteringFunctions/arm_fir_q7.o ./DSP/Source/FilteringFunctions/arm_fir_q7.su ./DSP/Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d ./DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o ./DSP/Source/FilteringFunctions/arm_fir_sparse_f32.su ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o
	-$(RM) ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./DSP/Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d ./DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o ./DSP/Source/FilteringFunctions/arm_fir_sparse_q15.su ./DSP/Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d ./DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o ./DSP/Source/FilteringFunctions/arm_fir_sparse_q31.su ./DSP/Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d ./DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o ./DSP/Source/FilteringFunctions/arm_fir_sparse_q7.su ./DSP/Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d ./DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o ./DSP/Source/FilteringFunctions/arm_iir_lattice_f32.su ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./DSP/Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d ./DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o ./DSP/Source/FilteringFunctions/arm_iir_lattice_q15.su ./DSP/Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d ./DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o ./DSP/Source/FilteringFunctions/arm_iir_lattice_q31.su ./DSP/Source/FilteringFunctions/arm_lms_f32.cyclo ./DSP/Source/FilteringFunctions/arm_lms_f32.d ./DSP/Source/FilteringFunctions/arm_lms_f32.o ./DSP/Source/FilteringFunctions/arm_lms_f32.su ./DSP/Source/FilteringFunctions/arm_lms_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_lms_init_f32.d ./DSP/Source/FilteringFunctions/arm_lms_init_f32.o ./DSP/Source/FilteringFunctions/arm_lms_init_f32.su ./DSP/Source/FilteringFunctions/arm_lms_init_q15.cyclo ./DSP/Source/FilteringFunctions/arm_lms_init_q15.d ./DSP/Source/FilteringFunctions/arm_lms_init_q15.o ./DSP/Source/FilteringFunctions/arm_lms_init_q15.su ./DSP/Source/FilteringFunctions/arm_lms_init_q31.cyclo ./DSP/Source/FilteringFunctions/arm_lms_init_q31.d ./DSP/Source/FilteringFunctions/arm_lms_init_q31.o ./DSP/Source/FilteringFunctions/arm_lms_init_q31.su ./DSP/Source/FilteringFunctions/arm_lms_norm_f32.cyclo ./DSP/Source/FilteringFunctions/arm_lms_norm_f32.d ./DSP/Source/FilteringFunctions/arm_lms_norm_f32.o ./DSP/Source/FilteringFunctions/arm_lms_norm_f32.su ./DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./DSP/Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./DSP/Source/FilteringFunctions/arm_lms_norm_q15.d ./DSP/Source/FilteringFunctions/arm_lms_norm_q15.o ./DSP/Source/FilteringFunctions/arm_lms_norm_q15.su ./DSP/Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./DSP/Source/FilteringFunctions/arm_lms_norm_q31.d ./DSP/Source/FilteringFunctions/arm_lms_norm_q31.o ./DSP/Source/FilteringFunctions/arm_lms_norm_q31.su ./DSP/Source/FilteringFunctions/arm_lms_q15.cyclo ./DSP/Source/FilteringFunctions/arm_lms_q15.d ./DSP/Source/FilteringFunctions/arm_lms_q15.o ./DSP/Source/FilteringFunctions/arm_lms_q15.su ./DSP/Source/FilteringFunctions/arm_lms_q31.cyclo ./DSP/Source/FilteringFunctions/arm_lms_q31.d ./DSP/Source/FilteringFunctions/arm_lms_q31.o ./DSP/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-DSP-2f-Source-2f-FilteringFunctions

